version: '3.7'

services:
  db:
    image: brightside-db
    build: ./tests/db
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=docker
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
  rabbitmq:
    image: rabbitmq:3-management
    environment:
      - RABBITMQ_ERLANG_COOKIE=SWQOKODSQALRPCLNMEQG
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
      - RABBITMQ_DEFAULT_VHOST=/
    ports:
      - "15672:15672"
      - "5672:5672"
  brightside-tests:
    container_name: brightside-tests
    build: ./
    environment:
      - BROKER=amqp://guest:guest@rabbitmq:5672
      - BRIGHTER_MESSAGE_STORE_URL=postgres://docker:password@db:5432/brightside_test
    depends_on:
       - rabbitmq
       - db


